import { Locale } from "../types";

export const UI_COPY = {
  zh: {
    subtitle: "AI 游戏竖切片工作台",
    languageLabel: "语言",
    languageValue: "中文",
    themePlaceholder: "描述你想做的游戏，例如：圆滚滚动物守护梦幻花园的竖屏生存游戏",
    compiling: "正在生成…",
    compile: "生成可玩蓝图",
    pipelineTitle: "工程进度",
    pipelineBadge: "Expert · 生产流水线",
    reviewState: "等待确认",
    runningState: "执行中",
    progressLabel: "生成进度",
    coldStartHint: "专家视图展示部门与工程 Gate；普通创作请使用简单模式的五步流程。",
    stages: [
      { name: "创意解析", desc: "世界观 / 目标体验" },
      { name: "设计规划", desc: "叙事 / 玩法" },
      { name: "运行时装配", desc: "架构" },
      { name: "状态与成长", desc: "架构 / 能力" },
      { name: "玩法组合", desc: "玩法卡 / Modifier" },
      { name: "可玩编译", desc: "代码 / Runtime" },
      { name: "视听装配", desc: "美术 / 音频" },
      { name: "证据验证", desc: "QA / 合规" }
    ],
    tabs: {
      departments: "部门 / Agent",
      prd: "设计方案",
      gameplay: "玩法与参数",
      manifest: "Manifest",
      vlm: "视觉证据"
    },
    emulator: {
      open: "打开试玩",
      openShort: "试玩",
      windowTitle: "WebGL H5 试玩",
      running: "运行中",
      status: "H5 运行状态",
      engine: "Phaser WebGL Runtime",
      unlocked: "已解锁",
      completed: "已完成",
      realm: "成长阶段",
      reset: "重置进度",
      sizeLabel: "试玩尺寸",
      sizes: {
        compact: "小",
        standard: "中",
        large: "大"
      },
      emptyTitle: "还没有可玩版本",
      emptyDesc: "先从「创意」生成一个蓝图，再进入试玩。"
    },
    prd: {
      badge: "Game Design Brief",
      file: "DesignSpec",
      desc: "当前作品的核心幻想、经济、成长与关卡设计",
      edit: "编辑设计",
      preview: "预览",
      save: "保存修改",
      discard: "放弃修改",
      overview: "作品概览与核心循环",
      title: "作品名称",
      currency: "主要货币 / 资源",
      themeColor: "主题配色",
      resources: "辅助资源",
      resource: "资源",
      realms: "成长阶段",
      realm: "阶段",
      nodes: "关卡 / 流程节点",
      levelPrefix: "第",
      levelSuffix: "段",
      nodeTitle: "节点标题",
      intro: "节点简介",
      mechanics: "核心玩法（只读）",
      goal: "局内目标（只读）",
      reward: "完成反馈 / 奖励文案",
      rewardHint: "叙事与反馈在这里编辑；玩法数值请进入「修改」。",
      playContract: "玩法合同摘要（只读）",
      playContractHint: "时长、难度、敌人、Boss 与胜利规则在「玩法与参数」中编辑。",
      openGameplay: "去修改玩法",
      empty: "还没有设计数据。先从「创意」生成第一个可玩蓝图。"
    },
    mechanics: {
      tap_reaction: "点击反应",
      collect_dodge: "收集与闪避",
      memory_sequence: "记忆序列"
    },
    gameplay: {
      desc: "数值参数可即时调整；玩法卡 / Modifier 的结构变化需要确认后应用。",
      cards: "玩法卡",
      revisions: "修订",
      manual: "高级人工审阅",
      pendingPatch: "待确认修改",
      discard: "丢弃",
      apply: "确认应用",
      node: "节点",
      adapter: "适配器",
      baseCard: "基础玩法",
      patchPolicy: "修改策略",
      policy1: "L0/L1：文案与参数即时应用并保存。",
      policy2: "L2：玩法卡与 Modifier 组合需要确认。",
      policy3: "L3/L4：Adapter / Runtime Core 修改需要人工审阅。",
      latest: "最近修订",
      noRevision: "暂无修订。应用第一个 Gameplay Patch 后会生成。",
      empty: "还没有可编辑的玩法数据。"
    },
    manifest: {
      desc: "专家模式下的结构化运行配置",
      valid: "结构有效",
      empty: "暂无 Manifest 数据。"
    },
    vlm: {
      title: "视觉证据 / VLM 审计",
      desc: "对 exact Candidate 截图进行布局、遮挡、文字与可读性检查",
      running: "正在分析截图…",
      run: "运行视觉审计",
      result: "视觉模型结论",
      pass: "PASS",
      notice: "NOTICE",
      prompt: "修正建议",
      promptAdd: "+ 下游视觉规则：",
      empty: "尚未执行视觉审计。"
    },
    logs: {
      title: "工程日志",
      collapse: "收起",
      button: "日志",
      empty: "暂无日志。",
      hint: "仅 Expert Mode 展示。"
    },
    footer: "LoreWeaver · Idea → Design → Play → Modify → Publish"
  },
  en: {
    subtitle: "AI game vertical-slice workbench",
    languageLabel: "Language",
    languageValue: "EN",
    themePlaceholder: "Describe a game, e.g. chubby animals defending a dreamy garden in a portrait survival game",
    compiling: "Creating…",
    compile: "Create Playable Blueprint",
    pipelineTitle: "Engineering Progress",
    pipelineBadge: "Expert · production pipeline",
    runningState: "Running",
    reviewState: "Needs review",
    progressLabel: "Generation progress",
    coldStartHint: "Expert view exposes departments and engineering gates. Normal creation uses the five-step Simple Mode flow.",
    stages: [
      { name: "Idea Parsing", desc: "World / target experience" },
      { name: "Design Planning", desc: "Narrative / gameplay" },
      { name: "Runtime Assembly", desc: "Architecture" },
      { name: "State & Progression", desc: "Architecture / ability" },
      { name: "Gameplay Composition", desc: "Cards / modifiers" },
      { name: "Playable Compile", desc: "Code / runtime" },
      { name: "Art & Audio", desc: "Presentation" },
      { name: "Evidence Validation", desc: "QA / compliance" }
    ],
    tabs: {
      departments: "Departments / Agents",
      prd: "Design",
      gameplay: "Gameplay & Params",
      manifest: "Manifest",
      vlm: "Visual Evidence"
    },
    emulator: {
      open: "Open Playtest",
      openShort: "Playtest",
      windowTitle: "WebGL H5 Playtest",
      running: "Running",
      status: "H5 runtime status",
      engine: "Phaser WebGL Runtime",
      unlocked: "Unlocked",
      completed: "Completed",
      realm: "Progression stage",
      reset: "Reset Progress",
      sizeLabel: "Playtest Size",
      sizes: {
        compact: "Small",
        standard: "Medium",
        large: "Large"
      },
      emptyTitle: "No playable build yet",
      emptyDesc: "Create a blueprint from Idea first, then enter Play."
    },
    prd: {
      badge: "Game Design Brief",
      file: "DesignSpec",
      desc: "Core fantasy, economy, progression, and flow for the current game",
      edit: "Edit Design",
      preview: "Preview",
      save: "Save Edits",
      discard: "Discard",
      overview: "Game overview and core loop",
      title: "Game title",
      currency: "Primary currency / resource",
      themeColor: "Theme color",
      resources: "Auxiliary resources",
      resource: "Resource",
      realms: "Progression stages",
      realm: "Stage",
      nodes: "Levels / flow nodes",
      levelPrefix: "Stage ",
      levelSuffix: "",
      nodeTitle: "Node title",
      intro: "Node intro",
      mechanics: "Core gameplay (read-only)",
      goal: "In-run goal (read-only)",
      reward: "Completion feedback / reward copy",
      rewardHint: "Edit narrative feedback here; tune gameplay values in Modify.",
      playContract: "Gameplay contract summary (read-only)",
      playContractHint: "Duration, difficulty, enemies, boss, and victory rules are edited under Gameplay & Params.",
      openGameplay: "Modify Gameplay",
      empty: "No design data yet. Create the first playable blueprint from Idea."
    },
    mechanics: {
      tap_reaction: "Tap reaction",
      collect_dodge: "Collect & dodge",
      memory_sequence: "Memory sequence"
    },
    gameplay: {
      desc: "Numeric knobs apply immediately; structural gameplay-card / modifier changes require confirmation.",
      cards: "Gameplay cards",
      revisions: "Revisions",
      manual: "Advanced manual review",
      pendingPatch: "Pending change",
      discard: "Discard",
      apply: "Apply",
      node: "Node",
      adapter: "Adapter",
      baseCard: "Base gameplay",
      patchPolicy: "Change policy",
      policy1: "L0/L1: copy and numeric params apply immediately and save.",
      policy2: "L2: gameplay card and modifier changes require confirmation.",
      policy3: "L3/L4: adapter/runtime-core changes require manual review.",
      latest: "Latest revisions",
      noRevision: "No revision yet. Apply the first gameplay patch to create one.",
      empty: "No editable gameplay data yet."
    },
    manifest: {
      desc: "Structured runtime configuration exposed in Expert Mode",
      valid: "Structure valid",
      empty: "No manifest data."
    },
    vlm: {
      title: "Visual Evidence / VLM Audit",
      desc: "Checks layout, occlusion, text, and readability on the exact Candidate screenshot",
      running: "Analyzing screenshot…",
      run: "Run Visual Audit",
      result: "Visual model verdict",
      pass: "PASS",
      notice: "NOTICE",
      prompt: "Repair guidance",
      promptAdd: "+ Downstream visual rule:",
      empty: "No visual audit yet."
    },
    logs: {
      title: "Engineering Logs",
      collapse: "Collapse",
      button: "Logs",
      empty: "No logs yet.",
      hint: "Visible in Expert Mode only."
    },
    footer: "LoreWeaver · Idea → Design → Play → Modify → Publish"
  }
} as const;

export type UiLocale = Locale;
