import { Locale } from "../types";

export const UI_COPY = {
  zh: {
    subtitle: "自主同人 H5 游戏智能生成引擎 v3.0",
    languageLabel: "语言",
    languageValue: "中文",
    themePlaceholder: "输入你想生成的个人题材（例如：东方玄幻、星海学院、赛博修行...）",
    compiling: "正在生成蓝图…",
    compile: "生成蓝图",
    pipelineTitle: "制作进度",
    pipelineBadge: "阶段 · 1.1–3.3 · 部门映射",
    reviewState: "等待人机确认",
    runningState: "冷启动中",
    progressLabel: "冷启动进度",
    coldStartHint:
      "制作主路径在「部门筹备台」。步骤亮灯=相关部门确认状态。顶栏「生成蓝图」仅用于整包冷启动/重建。",
    stages: [
      { name: "DNA 萃取 (1.1)", desc: "世界观组" },
      { name: "大纲规划 (1.2)", desc: "叙事组 · 玩法组" },
      { name: "宿主架设 (2.1)", desc: "架构组" },
      { name: "状态注入 (2.2)", desc: "架构组 · 能力组" },
      { name: "特性包 (2.3)", desc: "架构 · 玩法 · 能力" },
      { name: "物理编译 (3.1)", desc: "代码组 · 玩法组" },
      { name: "视听强化 (3.2)", desc: "美术 · 音频 · 代码" },
      { name: "多模审计 (3.3)", desc: "质检组 · 合规组" }
    ],
    tabs: {
      departments: "部门筹备台",
      prd: "作品设计方案",
      gameplay: "玩法卡工作台",
      manifest: "游戏配置清单",
      vlm: "VLM 视觉审计"
    },
    emulator: {
      open: "打开 WebGL 模拟器",
      openShort: "WebGL 模拟器",
      windowTitle: "WebGL H5 模拟器",
      running: "运行中",
      status: "H5 沙盒运行状态",
      engine: "Phaser v3.60 • WebGL 运行中",
      unlocked: "已解锁",
      completed: "已通关",
      realm: "修仙境界",
      reset: "重置进度",
      sizeLabel: "模拟器尺寸",
      sizes: {
        compact: "小 (360px)",
        standard: "中 (440px)",
        large: "大 (520px)"
      },
      emptyTitle: "未检测到修真配置",
      emptyDesc: "请先选择 workspace，或用顶栏「生成蓝图」冷启动一份 GDD，再在部门筹备台推进制作。"
    },
    prd: {
      badge: "游戏企划案 / GDD",
      file: "docs/01_PRD.md",
      desc: "系统自动生成的同人小说游戏设计文案与数值蓝图",
      edit: "编辑方案",
      preview: "预览方案",
      save: "保存修改",
      discard: "放弃修改",
      overview: "IP 特征指数与主要经济循环",
      title: "同人作品名称",
      currency: "主要等价值代币",
      themeColor: "智能配色方案",
      resources: "辅助资源",
      resource: "资源",
      realms: "修真境界等阶层级表",
      realm: "境界等阶",
      nodes: "主线十二关节点卡片配置",
      levelPrefix: "第",
      levelSuffix: "关",
      nodeTitle: "关卡标题",
      intro: "关卡简介",
      mechanics: "关卡玩法（只读）",
      goal: "局内目标（只读）",
      reward: "通关造化文案",
      rewardHint: "此处写奖励叙事文案；具体数值请在「玩法卡工作台」调整。",
      playContract: "玩法合同摘要（只读）",
      playContractHint: "时长 / 难度 / 敌人池 / Boss / 胜利模式仅在玩法卡工作台编辑。",
      openGameplay: "去玩法卡工作台",
      empty: "尚未获得企划数据。请在页面上方一键编译同人 IP 题材。"
    },
    mechanics: {
      tap_reaction: "敏捷聚灵 (Tap)",
      collect_dodge: "虚空飞渡 (Dodge)",
      memory_sequence: "心魂律动 (Memory)"
    },
    gameplay: {
      desc: "参数旋钮（L1）即时生效并写回；换玩法卡/挂载机制（L2）需确认后写入 revision。",
      cards: "玩法卡",
      revisions: "修订",
      manual: "L3/L4 人工审阅",
      pendingPatch: "待确认 Patch",
      discard: "丢弃",
      apply: "确认应用",
      node: "节点",
      adapter: "适配器",
      baseCard: "基础玩法卡",
      patchPolicy: "Patch 策略",
      policy1: "L0/L1：文案与参数（如 durationSec）即时生效并写回 manifest。",
      policy2: "L2：玩法卡与 modifier 组合，需要确认后应用。",
      policy3: "L3/L4：adapter/core 修改，必须人工审阅后再进入实现。",
      latest: "最近修订",
      noRevision: "暂无 revision。确认第一个 gameplay patch 后会生成。",
      empty: "尚未加载 manifest，无法管理玩法卡。"
    },
    manifest: {
      desc: "数据持久化主数据注册列表",
      valid: "JSON 规范格式验证通过",
      empty: "尚未保存清单数据。请编译小说 IP 生成实时内容。"
    },
    vlm: {
      title: "双视口多模态视觉智能审计",
      desc: "通过大语言视觉模型自动高差对比分析、重叠检测与文本折行溢出评估",
      running: "正在抓取像素矩阵...",
      run: "运行实时视觉审计",
      result: "智能视觉多模态大模型判定结论",
      pass: "成功(PASS)",
      notice: "提示(NOTICE)",
      prompt: "向后传递之 Prompt 知识蒸馏重排",
      promptAdd: "+ 提示分支追加优化规约:",
      empty: "尚未执行视觉审计。点击“运行实时视觉审计”抓取游戏视窗渲染树检查。"
    },
    logs: {
      title: "工作台实时日志",
      collapse: "收起",
      button: "日志",
      empty: "日志处于被动监听。",
      hint: "主路径：部门筹备台。需要整包重建时再用顶栏「生成蓝图」。"
    },
    footer: "LoreWeaver 制作工作台 · 部门筹备为主 · Phaser v3 WebGL 沙盒"
  },
  en: {
    subtitle: "AI-assisted personal H5 game workbench v3.0",
    languageLabel: "Language",
    languageValue: "EN",
    themePlaceholder: "Enter a personal theme, e.g. academy fantasy, star cultivation, cyber trials...",
    compiling: "Building blueprint…",
    compile: "Generate Blueprint",
    pipelineTitle: "Production Progress",
    pipelineBadge: "Stages · 1.1–3.3 · depts",
    runningState: "Cold start",
    reviewState: "Needs review",
    progressLabel: "Cold-start progress",
    coldStartHint:
      "Main path is the Dept Prep Desk. Step lights follow department confirms. Header button is full blueprint cold-start only.",
    stages: [
      { name: "DNA Extraction (1.1)", desc: "World dept" },
      { name: "Outline Planning (1.2)", desc: "Narrative · Gameplay" },
      { name: "Host Setup (2.1)", desc: "Architecture" },
      { name: "State Injection (2.2)", desc: "Architecture · Ability" },
      { name: "Feature Pack (2.3)", desc: "Arch · Gameplay · Ability" },
      { name: "Mechanics (3.1)", desc: "Code · Gameplay" },
      { name: "Art & Audio (3.2)", desc: "Art · Audio · Code" },
      { name: "QA (3.3)", desc: "QA · Compliance" }
    ],
    tabs: {
      departments: "Dept Prep Desk",
      prd: "Design Brief",
      gameplay: "Gameplay Cards",
      manifest: "Manifest JSON",
      vlm: "VLM Visual Audit"
    },
    emulator: {
      open: "Open WebGL Emulator",
      openShort: "WebGL Emulator",
      windowTitle: "WebGL H5 Emulator",
      running: "Running",
      status: "H5 sandbox status",
      engine: "Phaser v3.60 • WebGL active",
      unlocked: "Unlocked",
      completed: "Cleared",
      realm: "Realm",
      reset: "Reset progress",
      sizeLabel: "Simulator Size",
      sizes: {
        compact: "Small (360px)",
        standard: "Medium (440px)",
        large: "Large (520px)"
      },
      emptyTitle: "No game spec detected",
      emptyDesc: "Load a workspace or use Generate Blueprint for a cold start, then continue on the Dept Prep Desk."
    },
    prd: {
      badge: "Game Design Brief / GDD",
      file: "docs/01_PRD.md",
      desc: "Generated design copy, economy, and level blueprint",
      edit: "Edit Brief",
      preview: "Preview",
      save: "Save Edits",
      discard: "Discard",
      overview: "IP signals and economy loop",
      title: "Work title",
      currency: "Primary currency",
      themeColor: "Theme color",
      resources: "Auxiliary resources",
      resource: "Resource",
      realms: "Progression realms",
      realm: "Realm",
      nodes: "Main 12 level cards",
      levelPrefix: "Stage",
      levelSuffix: "",
      nodeTitle: "Level title",
      intro: "Level intro",
      mechanics: "Mechanic (read-only)",
      goal: "In-run goal (read-only)",
      reward: "Reward narrative",
      rewardHint: "Write reward story text here; numeric rewards belong in the Gameplay Workbench.",
      playContract: "Play contract summary (read-only)",
      playContractHint: "Duration / difficulty / enemy pool / boss / victory mode are edited only in the Gameplay Workbench.",
      openGameplay: "Open Gameplay Workbench",
      empty: "No design data yet. Cold-start a blueprint first."
    },
    mechanics: {
      tap_reaction: "Tap reaction",
      collect_dodge: "Collect & dodge",
      memory_sequence: "Memory sequence"
    },
    gameplay: {
      desc: "Param knobs apply immediately (L1). Card/modifier combos need confirm (L2) before revision.",
      cards: "cards",
      revisions: "revisions",
      manual: "L3/L4 manual review",
      pendingPatch: "Pending Patch",
      discard: "Discard",
      apply: "Apply",
      node: "Node",
      adapter: "adapter",
      baseCard: "Base card",
      patchPolicy: "Patch Policy",
      policy1: "L0/L1: copy and numeric params (e.g. durationSec) apply immediately and save.",
      policy2: "L2: gameplay card and modifier changes need confirmation.",
      policy3: "L3/L4: adapter/core edits require manual review before implementation.",
      latest: "Latest Revisions",
      noRevision: "No revision yet. Apply the first gameplay patch to create one.",
      empty: "Manifest is not loaded, so gameplay cards cannot be managed."
    },
    manifest: {
      desc: "Primary persisted game data registry",
      valid: "JSON schema format looks valid",
      empty: "No manifest yet. Use Generate Blueprint for a cold start."
    },
    vlm: {
      title: "Dual-viewport multimodal visual audit",
      desc: "Checks contrast, overlap, and text wrapping with a visual model workflow",
      running: "Capturing pixel matrix...",
      run: "Run Visual Audit",
      result: "Visual model verdict",
      pass: "PASS",
      notice: "NOTICE",
      prompt: "Prompt reflow notes",
      promptAdd: "+ Added downstream prompt rule:",
      empty: "No visual audit yet. Run the audit to inspect the game viewport."
    },
    logs: {
      title: "Workbench logs",
      collapse: "Collapse",
      button: "Logs",
      empty: "Logs are idle.",
      hint: "Main path: Dept Prep Desk. Use Generate Blueprint only for full rebuilds."
    },
    footer: "LoreWeaver production desk · department-first HITL · Phaser v3 WebGL sandbox"
  }
} as const;
